package com.example.myproject.Utils;

import android.app.Activity;

/**
 * Created by Admin on 17-01-2018.
 */

public class myproject_Common extends Activity
{
    public static String apk_version = "";
    public static String School_id = "";
    public static String apk_name = "";
    public static String status="";
    public static String image_test = "";
    public static String camera_volunteer = "";
    public static String camera_video = "";
    public static String user_id="";
    public static String am_pm_from="";
    public static String employee_check_in="";
    public static String  type_media= "";
    public static String  check_image_video= "";
    public static String  program_details= "";
    public static String  program_name= "";
    public static String  program_activity_video= "";
    public static String  program_activity_image_1= "";
    public static String present_emp_att="";
    public static String present_emp_check="";
    public static String absent_emp_att="";
    public static String student_id="";
    public static String absent_emp_check="";
    public static String employee_check_out="";
    public static String am_pm_to="";
    public static String hours_mins_to="";
    public static String employee_check="";
    public static int session_count;
    public static String session_count_present="";
    public static String session_count_all="";
    public static String session_count_absent="";
    public static String hours_mins_from_check="";
    public static String session_count_total="";
    public static String hours_mins_to_check="";
    public static String hours_mins_to_save="";
    public static String hours_mins_from_save="";
    public static String Class_id="";
    public static String school_allocate_id="";
    public static String school_allocate_name="";
    public static String school_allocate_hours="";
    public static int hours_to;
    public static int hours_from;

    public static String total_time_hrs="";
    public static String apk = "";
    public static String user_first_name="";
    public static String User_Name="";
    public static String Password="";
    public static String user_last_name="";
    public static String hours_mins_from="";
    public static String user_username="";
    public static String user_email="";
    public static int scholl_allocate_days=0;
    public static String search_value="";
    public static String user_role_id="";
    public static String value_type="";
    public static String value_name="";
    public static String user_designation="";
    public static String user_phone="";
    public static String user_company_id="";
    public static String approve_screen="";
    public static String company_name="";
    public static String user_office_id="";
    public static String user_login_url="";
    public static String user_profile_img="";
    public static String user_emp_id="";
    public static String user_incharge_name="";
    public static String user_incharge_phone="";
    public static String user_incharge_id="";
    public static String currentaddress="";
    public static String subLocality="";
    public static String time="";
    public static String date="";
    public static String check="";
    public static int previous_start =0;
    public static String gpsenabled="";
    public static String previous_start_check;
    public static String employee_leave_date_save;
    public static String school_leave_date_save;
    public static String employee_leave_date_show;
    public static String school_leave_date_show;
    public static String employee_leave_detail_id;
    public static String employee_leave_detail_office_id;
    public static String employee_leave_detail_emp_id;
    public static String employee_leave_detail_month;
    public static String employee_leave_detail_year;
    public static String employee_leave_detail_present;
    public static String employee_leave_detail_absent;
    public static String employee_leave_detail_half_day;
    public static String employee_leave_detail_lop;
    public static String employee_leave_detail_permission;
    public static String employee_leave_detail_casual_leave;
    public static String employee_leave_detail_earning_leave;
    public static String employee_leave_detail_medical_leave;
    public static String employee_leave_detail_casual_claimed;
    public static String employee_leave_detail_earning_claimed;
    public static String employee_leave_detail_medical_claimed;
    public static String employee_leave_detail_medical_rem;
    public static String employee_leave_detail_casual_rem;
    public static String employee_leave_detail_earning_rem;
    public static String employee_leave_detail_onduty;
    public static String employee_leave_detail_field_work;
    public static String total_leave;
    public static String device_id="";
    public static String check_in="";
    public static String checkout="";
    public static String lunchout="";
    public static String lunchin="";
    public static String permission1checkout="";
    public static String permissioncheck="";
    public static String permission_count="";
    public static String permission_text="";
    public static String permission1checkin="";
    public static String permission2checkout="";
    public static String permission2checkin="";
    public static String total_hrs="";
    public static String lunch_hrs="";
    public static String leave_atten="";
    public static String employee_leave_office_id="";
    public static String school_leave_office_id="";
    public static String employee_leave_emp_id="";
    public static String school_leave_emp_id="";
    public static String employee_leave_profile="";
    public static String school_leave_profile="";
    public static String employee_leave_designation="";
    public static String school_leave_designation="";
    public static String employee_leave_reason="";
    public static String school_leave_reason="";
    public static String employee_leave_phone="";
    public static String school_leave_phone="";
    public static String employee_leave_email="";
    public static String school_leave_email="";
    public static String employee_leave_name="";
    public static String school_leave_name="";
    public static String check_leave_list="0";
    public static int n3 = 0;
    public static int n1 = 0;
    public static int leave_COUNT = 0;
    public static int newmonth = 0;
    public static String date_to = "";
    public static String date_from = "";
    public static String reason = "";
    public static String employee_name = "";
    public static String employee_half_full = "";
    public static String employee_claim_leave = "";
    public static String employee_id = "";
    public static String employee_leave_days_count = "";
    public static String employee_from_date = "";
    public static String employee_to_date = "";
    public static String employee_entry_date_time = "";
    public static String employee_reason = "";
    public static String employee_designation = "";
    public static String employee_profile = "";
    public static String employee_casual_leave = "";
    public static String employee_casual_leave_rem = "";
    public static String employee_earning_leave = "";
    public static String employee_earning_leave_rem = "";
    public static String employee_onduty = "";
    public static String employee_field_work = "";
    public static String employee_Pre_post_lunch = "";
    public static String employee_medical_leave = "";
    public static String employee_medical_leave_rem = "";
    public static String employee_main_id = "";
    public static String school_main_id = "";
    public static String employee_incharge_name = "";
    public static String employee_office_id = "";
    public static String employee_approved = "";

    public static String leave_days_count="1";
    public static double leave_days = 0.0;
    public static String leave_type = "LOP";
    public static String leave_mode = "Full Day";
    public static String leave_day_lunch = "1";
    public static String leave_day_lunch_mode = "Pre Lunch";
    public static double casual_leave = 0.0;
    public static double earning_leave = 0.0;
    public static double medical_leave = 0.0;



}